/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DosisRouteImport } from './routes/dosis'
import { Route as EscanerRouteImport } from './routes/escaner'
import { Route as PerfilRouteImport } from './routes/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DosisRoute = DosisRouteImport.update({
  id: '/dosis',
  path: '/dosis',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanerRoute = EscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dosis' | '/escaner' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dosis' | '/escaner' | '/perfil'
  id: '__root__' | '/' | '/dosis' | '/escaner' | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DosisRoute: typeof DosisRoute
  EscanerRoute: typeof EscanerRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosis': {
      id: '/dosis'
      path: '/dosis'
      fullPath: '/dosis'
      preLoaderRoute: typeof DosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escaner': {
      id: '/escaner'
      path: '/escaner'
      fullPath: '/escaner'
      preLoaderRoute: typeof EscanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DosisRoute: DosisRoute,
  EscanerRoute: EscanerRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
