/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DosisRouteImport } from './routes/dosis'
import { Route as EscanerRouteImport } from './routes/escaner'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AuthenticatedHoyRouteImport } from './routes/_authenticated/hoy'
import { Route as ApiPublicHooksDoseRemindersRouteImport } from './routes/api/public/hooks/dose-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DosisRoute = DosisRouteImport.update({
  id: '/dosis',
  path: '/dosis',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanerRoute = EscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHoyRoute = AuthenticatedHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksDoseRemindersRoute =
  ApiPublicHooksDoseRemindersRouteImport.update({
    id: '/api/public/hooks/dose-reminders',
    path: '/api/public/hooks/dose-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/api/public/hooks/dose-reminders': typeof ApiPublicHooksDoseRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/api/public/hooks/dose-reminders': typeof ApiPublicHooksDoseRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dosis': typeof DosisRoute
  '/escaner': typeof EscanerRoute
  '/perfil': typeof PerfilRoute
  '/_authenticated/hoy': typeof AuthenticatedHoyRoute
  '/api/public/hooks/dose-reminders': typeof ApiPublicHooksDoseRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dosis'
    | '/escaner'
    | '/perfil'
    | '/hoy'
    | '/api/public/hooks/dose-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dosis'
    | '/escaner'
    | '/perfil'
    | '/hoy'
    | '/api/public/hooks/dose-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dosis'
    | '/escaner'
    | '/perfil'
    | '/_authenticated/hoy'
    | '/api/public/hooks/dose-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DosisRoute: typeof DosisRoute
  EscanerRoute: typeof EscanerRoute
  PerfilRoute: typeof PerfilRoute
  ApiPublicHooksDoseRemindersRoute: typeof ApiPublicHooksDoseRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosis': {
      id: '/dosis'
      path: '/dosis'
      fullPath: '/dosis'
      preLoaderRoute: typeof DosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escaner': {
      id: '/escaner'
      path: '/escaner'
      fullPath: '/escaner'
      preLoaderRoute: typeof EscanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hoy': {
      id: '/_authenticated/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof AuthenticatedHoyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/dose-reminders': {
      id: '/api/public/hooks/dose-reminders'
      path: '/api/public/hooks/dose-reminders'
      fullPath: '/api/public/hooks/dose-reminders'
      preLoaderRoute: typeof ApiPublicHooksDoseRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHoyRoute: typeof AuthenticatedHoyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHoyRoute: AuthenticatedHoyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DosisRoute: DosisRoute,
  EscanerRoute: EscanerRoute,
  PerfilRoute: PerfilRoute,
  ApiPublicHooksDoseRemindersRoute: ApiPublicHooksDoseRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
